"""
Raw Command Generator for Oblivion Character Data Import Manager
Generates raw console commands that can be used in the Construction Set or console.
"""

import os
from pathlib import Path
from typing import List, Dict, Any, Optional


def parse_remastered_load_order(file_path: Path) -> Dict[str, int]:
    """
    Parse Oblivion Remastered Plugins.txt file.
    This file has a simpler format - just one mod per line.

    Args:
        file_path: Path to the Plugins.txt file

    Returns:
        Dictionary mapping mod names to their hex indices
    """
    load_order = {}
    index = 0

    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()

            # Skip empty lines
            if not line:
                continue

            # Each line is a mod name
            mod_name = line
            load_order[mod_name] = index
            index += 1

    return load_order


def create_load_order_mapping(old_load_order: Dict[str, int], new_load_order: Dict[str, int]) -> Dict[str, str]:
    """
    Create a mapping from old hex indices to new hex indices based on mod names.

    Args:
        old_load_order: Dictionary of {mod_name: index} for old Oblivion
        new_load_order: Dictionary of {mod_name: index} for Remastered

    Returns:
        Dictionary mapping old hex prefixes to new hex prefixes
        Example: {"06": "09", "07": "0A"}
    """
    mapping = {}

    for mod_name, old_index in old_load_order.items():
        if mod_name in new_load_order:
            new_index = new_load_order[mod_name]
            old_hex = f"{old_index:02X}"
            new_hex = f"{new_index:02X}"

            if old_hex != new_hex:
                mapping[old_hex] = new_hex

    return mapping


def remap_form_id_for_remastered(form_id: str, hex_mapping: Dict[str, str]) -> str:
    """
    Remap a form ID using the hex mapping.

    Args:
        form_id: The original form ID (e.g., "06004B9B")
        hex_mapping: Dictionary mapping old hex to new hex (e.g., {"06": "09"})

    Returns:
        The remapped form ID (e.g., "09004B9B")
    """
    if len(form_id) >= 2:
        prefix = form_id[:2].upper()

        # Don't remap vanilla (00) or dynamic (FF) form IDs
        if prefix == "00" or prefix == "FF":
            return form_id

        if prefix in hex_mapping:
            return hex_mapping[prefix] + form_id[2:]

    return form_id


def generate_raw_commands(
    preset_data: Dict[str, Any],
    export_options: Dict[str, bool],
    hex_mapping: Optional[Dict[str, str]] = None
) -> List[str]:
    """
    Generate raw console commands from preset data.

    Args:
        preset_data: The preset data dictionary
        export_options: Dictionary of what to export
        hex_mapping: Optional dictionary mapping old hex to new hex (for Remastered)

    Returns:
        List of command strings
    """
    commands = []

    # Header comment
    commands.append("; ========================================")
    commands.append("; Raw Commands for Oblivion")
    if "character" in preset_data:
        char_name = preset_data["character"].get("name", "Unknown")
        commands.append(f"; Character: {char_name}")
    commands.append("; Generated by Varla Character Data Manager")
    commands.append("; ========================================")
    commands.append("")

    # Items
    if export_options.get("items", True) and "items" in preset_data:
        commands.append("; ===== ITEMS =====")
        for item in preset_data["items"]:
            form_id = item.get("formId", "")
            quantity = item.get("quantity", 1)
            name = item.get("name", "Unknown")

            # Remap form ID if mapping is provided
            if hex_mapping:
                form_id = remap_form_id_for_remastered(form_id, hex_mapping)

            # Add comment with item name
            commands.append(f"; {name}")
            commands.append(f"player.additem {form_id} {quantity}")
        commands.append("")

    # Spells
    if export_options.get("spells", True) and "spells" in preset_data:
        commands.append("; ===== SPELLS =====")
        for spell in preset_data["spells"]:
            form_id = spell.get("formId", "")
            name = spell.get("name", "Unknown")

            # Remap form ID if mapping is provided
            if hex_mapping:
                form_id = remap_form_id_for_remastered(form_id, hex_mapping)

            # Add comment with spell name
            commands.append(f"; {name}")
            commands.append(f"player.addspell {form_id}")
        commands.append("")

    # Spells to Remove
    if export_options.get("spells", True) and "spellsToRemove" in preset_data:
        commands.append("; ===== REMOVE SPELLS =====")
        for spell in preset_data["spellsToRemove"]:
            form_id = spell.get("formId", "")
            name = spell.get("name", "Unknown")

            # Remap form ID if mapping is provided
            if hex_mapping:
                form_id = remap_form_id_for_remastered(form_id, hex_mapping)

            # Add comment with spell name
            commands.append(f"; {name}")
            commands.append(f"player.removespell {form_id}")
        commands.append("")

    # Character Level
    if export_options.get("character", True) and "character" in preset_data:
        character = preset_data["character"]
        if "level" in character:
            commands.append("; ===== CHARACTER LEVEL =====")
            level = character["level"]
            commands.append(f"player.setLevel {level}")
            commands.append("")

    # Attributes
    if export_options.get("attributes", True) and "attributes" in preset_data:
        commands.append("; ===== ATTRIBUTES =====")
        for attr_name, attr_value in preset_data["attributes"].items():
            commands.append(f"player.SetAV {attr_name} {attr_value}")
        commands.append("")

    # Skills
    if export_options.get("skills", True) and "skills" in preset_data:
        commands.append("; ===== SKILLS =====")
        for skill_name, skill_value in preset_data["skills"].items():
            commands.append(f"player.SetAV {skill_name} {skill_value}")
        commands.append("")

    # Statistics (Fame, Infamy, Bounty)
    if export_options.get("statistics", True) and "statistics" in preset_data:
        stats = preset_data["statistics"]

        if "fame" in stats:
            commands.append("; ===== FAME =====")
            commands.append(f"SetPCFame {stats['fame']}")
            commands.append("")

        if "infamy" in stats:
            commands.append("; ===== INFAMY =====")
            commands.append(f"SetPCInfamy {stats['infamy']}")
            commands.append("")

        if "bounty" in stats:
            commands.append("; ===== BOUNTY =====")
            commands.append(f"player.SetCrimeGold {stats['bounty']}")
            commands.append("")

    # Factions
    if export_options.get("factions", True) and "factions" in preset_data:
        commands.append("; ===== FACTIONS =====")
        for faction in preset_data["factions"]:
            form_id = faction.get("formId", "")
            rank = faction.get("rank", 0)
            name = faction.get("name", "Unknown")

            # Remap form ID if mapping is provided
            if hex_mapping:
                form_id = remap_form_id_for_remastered(form_id, hex_mapping)

            # Add comment with faction name
            commands.append(f"; {name}")
            commands.append(f"player.SetFactionRank {form_id} {rank}")
        commands.append("")

    # Completed Quests
    if export_options.get("completedQuests", True) and "quests" in preset_data:
        commands.append("; ===== COMPLETED QUESTS =====")
        for quest_id in preset_data["quests"]:
            commands.append(f"; {quest_id}")
            commands.append(f"SetStage {quest_id} 100")
        commands.append("")

    # Footer
    commands.append("; ===== END OF COMMANDS =====")

    return commands


def save_raw_commands_to_file(commands: List[str], file_path: Path) -> None:
    """
    Save raw commands to a text file.

    Args:
        commands: List of command strings
        file_path: Path to save the file
    """
    with open(file_path, 'w', encoding='utf-8') as f:
        for command in commands:
            f.write(command + '\n')
        f.flush()  # Force write to disk
        os.fsync(f.fileno())  # Ensure OS writes to disk immediately
